#!/usr/bin/bash
#SBATCH --job-name=swei_jedi
#SBATCH --nodes=1
#SBATCH --ntasks=6
#SBATCH --time=0:30:00
#SBATCH --account=%ACCOUNT%
#SBATCH --partition=%PARTITION%
#SBATCH --qos=%QOS%
#SBATCH --output=%LOGFILE%

set -x

source /etc/bashrc
source /home/shihwei/.bashrc
load_skylab
module list

export SLURM_EXPORT_ENV=ALL
export HDF5_USE_FILE_LOCKING=FALSE

ulimit -s unlimited || true
ulimit -v unlimited || true

