#!/usr/bin/bash
#SBATCH --job-name=swei_jedi
#SBATCH --nodes=1
##SBATCH --ntasks=6
##SBATCH --cpus-per-task=1
#SBATCH --account=da-cpu
#SBATCH --partition=orion
#SBATCH --qos=batch
#SBATCH --time=0:30:00
#SBATCH --output=/work2/noaa/jcsda/shihwei/slurmlogs/testjedi.%j

set -x

source /etc/bashrc
source /home/shihwei/.bashrc
load_skylab
module list

export SLURM_EXPORT_ENV=ALL
export HDF5_USE_FILE_LOCKING=FALSE

ulimit -s unlimited || true
ulimit -v unlimited || true

